### ISSUE TITLE
antd-mobile如何把字体图标保存到本地引入

### ISSUE THREAD

**Issue by sniperyan** [ant-design/antd-init#124]
antd mobile 的目录和 antd不一样，试着antd的不行啊

**Comment by sorrycc** [comment]
为什么要保存到本地?

**Comment by sniperyan** [comment]
@sorrycc  我用antd-mobile写了混合app，font-face里引用的路径在app里被解析成了本地的file，而不是发http请求或https请求去加载服务器上的

**Comment by sorrycc** [comment]
@afc163

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont

**Comment by sniperyan** [comment]
@afc163 请问一下import哪几个文件，目录不一样，例子是antd，我用的是antd-mobile

**Comment by chengky** [comment]
@sinperyan 
直接导入custom.less:

```less
#custom.less
@icon-url: "/resources/fonts/iconfont"; // 把 iconfont 地址改到本地
@font-face {
  font-family: 'anticon';
  src: url('@{icon-url}.eot'); /* IE9*/
  src: url('@{icon-url}.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('@{icon-url}.woff') format('woff'), /* chrome、firefox */
  url('@{icon-url}.ttf') format('truetype'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/
  url('@{icon-url}.svg#iconfont') format('svg'); /* iOS 4.1- */
}
```
